### ISSUE TITLE
Did the integration stopped working?

### ISSUE THREAD

**Issue by andrebbruno** [skelgaard/homeassistant-apsystems#15]
Tried rebooting the ECU, Home Assistant etc and nothing seems to be working since yesterday.

Are you guys seeing this as well?

**Comment by Shadyville08** [comment]
Yes, stopped working over here as well.

**Comment by skelgaard** [comment]
i can't do much, when https://apsystemsema.com/ema/ isn't working..... it should work again, when the website is up, but until then, we just have to wait or mail them and ask when it will be back

**Comment by sjakief** [comment]
> i can't do much, when https://apsystemsema.com/ema/ isn't working..... it should work again, when the website is up, but until then, we just have to wait or mail them and ask when it will be back

for some reason, your link goes to https://apsystemsema.com/ema/ema, when I go to https://apsystemsema.com/ema/index.action from a browser it works fine

**Comment by skelgaard** [comment]
i will look into it tomorrow :)

**Comment by devano1701** [comment]
I have got almost the same problem here. I did not get any sensor readings since installing the program. All five sensors are “Niet beschikbaar”.
I live in an apartment and have no direct access to the ECU-R, but I can read my PV panels through apsystemsema on the web and in the app.
It seems to me that there is no data coming from apsystemsema. I get the following error messages in the log.
Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.helpers.entity
Source: custom_components/apsystems/sensor.py:227 
Integration: apsystems (documentation) 
First occurred: 30 oktober 2022 om 07:33:08 (825 occurrences) 
Last logged: 11:28:12

Update for sensor.apsystems_energy_day fails
Update for sensor.apsystems_energy_latest fails
Update for sensor.apsystems_power_max_day fails
Update for sensor.apsystems_power_latest fails
Update for sensor.apsystems_date fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 710, in async_device_update
    raise exc
  File "/config/custom_components/apsystems/sensor.py", line 142, in async_update
    ap_data = await self._fetcher.data()
  File "/config/custom_components/apsystems/sensor.py", line 238, in data
    await self.run()
  File "/config/custom_components/apsystems/sensor.py", line 227, in run
    self.cache = result_data.json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In the code (sensor.py) is a _LOGGER function, but I cannot find any logs from this code.
Can you help me?

**Comment by daniel1204xx** [comment]
same issue for me .... .is there any chance to get it fixed and working again ? I can not find where I need to replace the URL :-( Can someone help ? Thanks :)

**Comment by skelgaard** [comment]
i have connection to their system again in my test, but gets an error on home assistant.... i'm working on which part of the request it is missing to make it work....
I hope to soon have it working again, but python is not my specialty but i'm working though it :)

**Comment by krizzziz** [comment]
> i have connection to their system again in my test, but gets an error on home assistant.... i'm working on which part of the request it is missing to make it work....
> I hope to soon have it working again, but python is not my specialty but i'm working though it :)

Any luck yet?

**Comment by devano1701** [comment]
I get a 403 Forbidden response from the login in line 198. 
Probably AP systems has changes their web interface.
I am not experienced enough to tackle this further.

**Comment by MORITZ0405** [comment]
Is it working ?

**Comment by skelgaard** [comment]
i have connection in phpstorm again, but i can't get it to work in python... i'm still trying though

**Comment by MORITZ0405** [comment]
What did you enter in php storm I could help you there

**Comment by MORITZ0405** [comment]
I think this is the problem ? https://apsystemsema.com/ema/ajax/getReportApiAjax/getPowerOnCurrentDayAjax

**Comment by skelgaard** [comment]
its something todo with python, cause there is nothing special in the queries

### Login
GET https://www.apsystemsema.com/ema/intoDemoUser.action?id=KEY

### Get Data
POST https://www.apsystemsema.com/ema/ajax/getReportApiAjax/getPowerOnCurrentDayAjax

queryDate=20221118&selectedValue=ECUID&systemId=SYSTEMID

**Comment by MORITZ0405** [comment]
![noooo](https://user-images.githubusercontent.com/60063969/203114829-5ffc4359-8325-429e-90d5-023c38795319.PNG)
No

**Comment by MORITZ0405** [comment]
Maybe python can't connect to https url

**Comment by skelgaard** [comment]
it has done before without problems

**Comment by skelgaard** [comment]
well i found out part of the problem...

2022-11-21 19:15:22.947 DEBUG (MainThread) [custom_components.apsystems.sensor] Sending login: https://www.apsystemsema.com/ema/intoDemoUser.action?id=XXXXXXX
2022-11-21 19:15:23.035 DEBUG (MainThread) [custom_components.apsystems.sensor] Login result:403

so its the login... working on it...

**Comment by devano1701** [comment]
I got the same results here.
When I run de request directly in python with the requests.py library I again get a 403. But if I run the request from VS Code I get a 200.
It seems that the python library request.py contains the problem. Or APSystems changed something on their website.

**Comment by MORITZ0405** [comment]
I think i Fixed it

**Comment by MORITZ0405** [comment]
I get a 200 directly in python

**Comment by skelgaard** [comment]
lets hear, or do a PR and i will merge :)

**Comment by MORITZ0405** [comment]
I changed something in my pycharm and now I get a 200

**Comment by MORITZ0405** [comment]
![dwdhzgft](https://user-images.githubusercontent.com/60063969/203142027-8a4d9a55-9926-4c9b-8ab3-c91425f52a8f.PNG)

**Comment by MORITZ0405** [comment]
xD

**Comment by MORITZ0405** [comment]
![pyyyyyyyyyyyyy](https://user-images.githubusercontent.com/60063969/203142205-617947ba-b2fd-4237-8f7a-f1a6312ff5f4.PNG)

**Comment by MORITZ0405** [comment]
It doesn't work in HACS

**Comment by skelgaard** [comment]
new release is out... give it a test

**Comment by MORITZ0405** [comment]
THX
